### ISSUE TITLE
"OSError: exception: access violation reading" while trying to exportc a proc who calls python 's function 

### ISSUE THREAD

**Issue by retsyo** [yglukhov/nimpy#168]
The idea is to expose functions from python in a normal DLL instead of python's PYD, so that other program language can use the functions without knowing how to embed python

for the `a.nim`
```nim
proc add*(x, y: int): int {. exportc, dynlib, nimcall .} = x+y

const
    ver* {. exportc.}= "2020"
    d {. exportc.}= 2020

proc fun1*() : string {.exportc, dynlib, nimcall.} =
    "I'm a Nim String"

proc fun2*() : cstring {.exportc, dynlib, nimcall.} =
    "I'm a CString"
```
I can get a DLL via `nim c -d:release -d:speed --app:lib a.nim`. The the following python code can call the functions in DLL
```python
import ctypes
DLL = ctypes.CDLL('a.dll')

print(DLL.add(10, 29))

DLL.fun1.restype = ctypes.c_char_p
print(DLL.fun1())

DLL.fun2.restype = ctypes.c_char_p
print(DLL.fun2())
```
well, I can't say 'without problem` because only function `add` and `fun2` return expected result. `fun1` does not, but there is no error at least

then I add
```nim
import nimpy
let os* {. exportc.}= pyImport("os")

proc cwd*(): string {. exportc, dynlib, nimcall  .} =
    return os.getcwd().to(string)
```
to `a.nim` and test the generated DLL(which has been copied to the directory where `python.exe` lives, so I think there is no PYTHONPATH problem) with
```
import ctypes

DLL = ctypes.CDLL('a.dll')

print(DLL.add(10, 29))
DLL.fun1.restype = ctypes.c_char_p
print(DLL.fun1())

DLL.fun2.restype = ctypes.c_char_p
print(DLL.fun2())

print(DLL.cwd())
```
but I get
```
39
b'\x10'
b"I'm a CString"
Traceback (most recent call last):
  File "call_dll.py", line 16, in <module>
    print(DLL.cwd())
OSError: exception: access violation reading 0x0000000000000025
```

so what is the problem? Thanks

**Comment by yglukhov** [comment]
In your 2nd example cwd returns string, which is not cstring. So that's one issue at least.

**Comment by yglukhov** [comment]
Also nimcall is fastcall on windows, which is probably not what you want.

**Comment by retsyo** [comment]
but `proc fun1*() : string`, which returns nim's string, can be called without OSError, though the result of `DLL.fun1` is not right.

**Comment by yglukhov** [comment]
Ah ok, I see. Does removing `nimcall` change anything?

**Comment by retsyo** [comment]
no, nothing changed

```nim
# a.nim
proc add*(x, y: int): int {. exportc, dynlib.} = x+y

const
    ver* {. exportc.}= "2020"
    d {. exportc.}= 2020

proc fun1*() : string {.exportc, dynlib.} =
    "I'm a Nim String"

proc fun2*() : cstring {.exportc, dynlib.} =
    "I'm a CString"

import nimpy
let os* {. exportc.}= pyImport("os")

proc cwd1*(): string {. exportc, dynlib.} =
    return os.getcwd().to(string)

proc cwd2*(): cstring {. exportc, dynlib.} =
    return cast[cstring](os.getcwd().to(string))
```
then 
```python
import ctypes

DLL = ctypes.CDLL('a.dll')

#~ DLL.NimMain()

print(DLL.add(10, 29))

DLL.fun1.restype = ctypes.c_char_p
print(DLL.fun1())

DLL.fun2.restype = ctypes.c_char_p
print(DLL.fun2())

#~ DLL.cwd1.restype = ctypes.c_char_p
#~ print(DLL.cwd1())

#~ DLL.cwd2.restype = ctypes.c_char_p
#~ print(DLL.cwd2())
```
says
```
>L:\prg\py\Anaconda3_64\python.exe -u "call_dll.py"
39
b'\x10'
b"I'm a CString"
Traceback (most recent call last):
  File "call_dll.py", line 16, in <module>
    print(DLL.cwd1())
OSError: exception: access violation reading 0x0000000000000025

>L:\prg\py\Anaconda3_64\python.exe -u "call_dll.py"
39
b'\x10'
b"I'm a CString"
Traceback (most recent call last):
  File "call_dll.py", line 19, in <module>
    print(DLL.cwd2())
OSError: exception: access violation reading 0x0000000000000025
```

**Comment by yglukhov** [comment]
Finally got around to test it, and can't reproduce with nim 1.4.2. Can you confirm?

As a side note, your example program is not that trivial to get right, i'm afraid. You have to learn about and account for nim GC initialization, stack bottom updates, tls emulation, stackTrace:off, and such.

**Comment by retsyo** [comment]
the same still happens with python 3.7.3, python 3.6.10 on windows 10 64bits
```
$ nim
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-01-25
Copyright (c) 2006-2021 by Andreas Rumpf
```

but I think I'd better embed python and call function's in python in source code.
