### ISSUE TITLE
Error when importing Nim file

### ISSUE THREAD

**Issue by nonimportant** [yglukhov/nimpy#251]
When I try to import a Nim file with nimpy these errors show up:
```
Error: unhandled exception: The system cannot find the file specified.
Error: unhandled exception: The system cannot find the file specified.
Error: unhandled exception: The system cannot find the file specified.
Error: unhandled exception: The system cannot find the file specified.
Error: unhandled exception: The system cannot find the file specified.
Error: unhandled exception: The system cannot find the file specified.
Error: execution of an external compiler program 'vccexe.exe /c --platform:amd64 /nologo /GL -DWIN32_LEAN_AND_MEAN /O2   /IC:\Nim\nim-1.6.2\lib /IC:\Users\xxxx\IdeaProjects\nimxpython /nologo /FoC:\Users\xxxx\nimcache\main__r\stdlib_strutils.nim.c.obj C:\Users\xxxx\nimcache\main__r\stdlib_strutils.nim.c' failed with exit code: 1
Error: unhandled exception: The system cannot find the file specified.
Error: unhandled exception: The system cannot find the file specified.
Error: unhandled exception: The system cannot find the file specified.
Error: unhandled exception: The system cannot find the file specified.
Error: unhandled exception: The system cannot find the file specified.
Error: unhandled exception: The system cannot find the file specified.
Error: unhandled exception: The system cannot find the file specified.
Traceback (most recent call last):
  File "C:\Users\xxxx\IdeaProjects\nimxpython\main.py", line 2, in <module>
    import main_
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 1271, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 946, in import_nim_code
    NimCompiler.compile_nim_code(
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 707, in compile_nim_code
    cls.check_compile_errors(errors, library, nim_args, output, tmp_cwd, warnings)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 494, in check_compile_errors
    raise NimCompileException(errors[0])
nimporter.NimCompileException: Error: unhandled exception: The system cannot find the file specified.
```

This is main.py:
```
import nimporter
import main_

main_.hello_world()
```

This is main_.nim:
```
import nimpy

proc hello_world() {.exportpy.} =
  echo "Hello World!"
```

**Comment by yglukhov** [comment]
I'm not sure if nim likes the trailing underline in identifiers, that might be the issue. In any case, the issue seems to originate from [nimporter](https://github.com/Pebaz/nimporter), please file the issue in that repo.
