### ISSUE TITLE
[Bug] Using nim procedures as Python decorators is not working

### ISSUE THREAD

**Issue by Ethosa** [yglukhov/nimpy#286]
```nim
type A* = ref object of PyNimObjectExperimental

proc get(self: A, path: string, callback: PyObject) {.exportpy.} =
    echo path
    echo repr(callback)
```

```py
app = A()

app.get("/", lambda x: print(...))  # Works!

@app.get("/")
def read_root():  # Doesn't works!
    return {"Hello": "World"}
```

### Output
```bash
/
ref 0000022a4f9630d0 --> [rawPyObj = ptr 0000022a4fdd3e20 --> []]
Traceback (most recent call last):
  File "............\testpy1.py", line 15, in <module>
    @app.get("/")
TypeError: get() takes exactly 3 arguments (1 given)
```

### Additional Context
If I change nim procedure:
```nim
proc get(self: A, path: string, callback: PyObject = nil) {.exportpy.} =
    echo path
    echo repr(callback)
```

so I get this error:
```bash
Traceback (most recent call last):
  File "............\testpy1.py", line 15, in <module>
    def read_root():
TypeError: 'NoneType' object is not callable
```

**Comment by yglukhov** [comment]
Try it in python, you'll get the same results. I believe you're expecting your python code to be expanded to smth like:
```py
app.get("/", read_root)
```
But that's not how decorators work in python. In fact your python code is equivalent to
```py
(app.get("/"))(read_root)
```

**Comment by Ethosa** [comment]
oh sorry for my mistake
